### ISSUE TITLE
显示结果的窗体无法拉伸, 不是很方便

### ISSUE THREAD

**Issue by ViCrack** [mr-m0nst3r/Burpy#15]
![图片](https://user-images.githubusercontent.com/18179821/102241167-9f188b80-3f33-11eb-9584-997b67e39cb7.png)

这个窗口无法使用鼠标拉伸
数据一多的话 不太方便查看

**Comment by mr-m0nst3r** [comment]
刚刚把窗口放大了，对swing还不熟悉，后面时间充足之后再来改。谢谢，也欢迎提PR
