### ISSUE TITLE
python3无法启动python2中没有Importlib.util

### ISSUE THREAD

**Issue by lanfei-4** [mr-m0nst3r/Burpy#17]
python3点击启动没有反应

python2启动提示
*** Burpy Console ***  Traceback (most recent call last):  File "C:\Users\JuiceWoo\AppData\Local\Temp\burpyServicePyro3.py", line 9, in    import importlib.util  ImportError: No module named util

python2的importlin本身就没有util

**Comment by mr-m0nst3r** [comment]
你的python版本是多少？可能跟python版本有关。我在用的是python3.9

**Comment by mr-m0nst3r** [comment]
@lanfei-4 刚刚更新了v2.4.3，你试一下行不行。

**Comment by mr-m0nst3r** [comment]
如果还有问题再打开吧，我先关闭这个了。
