### ISSUE TITLE
在porxy的history中可以解密，但是在repeaater不能使用

### ISSUE THREAD

**Issue by godzeo** [mr-m0nst3r/Burpy#21]
**Describe the bug**
在porxy的history中可以解密，但是在repeaater不能使用
**To Reproduce**

在porxy的history中可以正常解密，但是在repeaater不能使用

报错语句
rypt in BurpyService failed

'UnicodeDecodeError' object has no attribute 'encode'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS
 - Python: 3.8
 - Burpy:  v2.4.4
 - burpsuite 2021.7

**Burpy Scripts**
```
class MyCipher():

    def __init__(self, key='', iv=''):
        BS = 24
        if len(key) > 0:
            self.key = key.encode()
        if len(iv) > 0:
            self.iv = iv.encode()
        self.pad = lambda s: s + (BS - len(s.encode()) % BS) * chr(BS - len(s.encode()) % BS)
        self.unpad = lambda s: s[0:-ord(s[-1])]

    def decrypt(self, decryptText, cipher, mode=''):
        try:
            if cipher == 'des3':
                cipherX = DES3.new(self.key, DES3.MODE_CBC, self.iv)
            if mode == 'base64':
                decryptText = base64.b64decode(decryptText)
            return self.unpad(cipherX.decrypt(decryptText).decode())
        except Exception as e:
            return e
def decrypt(self, header, body):

        key = ''
        iv = ''
        destest = MyCipher(key, iv)
        _new_body = destest.decrypt(body, 'des3', 'base64')

```

**Additional context**
报错语句
rypt in BurpyService failed

'UnicodeDecodeError' object has no attribute 'encode'

**Comment by mr-m0nst3r** [comment]
你可以你的脚本中，写个`if __name__='__main__'`语句，把你的测试放到下面，直接执行这个脚本，这样就可以看下脚本是不是有问题。

解密之后有中文吗？我也遇到过有中文的，但没有出现这个问题 XD

**Comment by mr-m0nst3r** [comment]
长时间没有回复，先关闭了，有问题再打开
