### ISSUE TITLE
import frida的脚本，会出现如下报错

### ISSUE THREAD

**Issue by shu1qin9** [mr-m0nst3r/Burpy#22]
ImportError: dlopen(/Users/crystal/Library/Python/3.8/lib/python/site-packages/_frida.cpython-38-darwin.so, 2): no suitable image found. Did find:  /Users/crystal/Library/Python/3.8/lib/python/site-packages/_frida.cpython-38-darwin.so: no matching architecture in universal wrapper  /Users/crystal/Library/Python/3.8/lib/python/site-packages/_frida.cpython-38-darwin.so: no matching architecture in universal wrapper 

![image](https://user-images.githubusercontent.com/53843638/132443613-04358817-16af-4f69-a9aa-3dfc2d5ef86c.png)
![image](https://user-images.githubusercontent.com/53843638/132443632-c0eb48b7-8343-4d08-9489-d61cb9c2f273.png)

**Comment by mr-m0nst3r** [comment]
系统环境写一下吧，只看这个解决不了问题。

**Comment by mr-m0nst3r** [comment]
如有还有问题，再打开这个issue，暂时关闭了。

**Comment by shu1qin9** [comment]
> 系统环境写一下吧，只看这个解决不了问题。

系统环境是m1的mac，我感觉应该是Burp引用frida库的时候，不适配m1
