### ISSUE TITLE
POST表单处理<>有问题

### ISSUE THREAD

**Issue by hack2012** [mr-m0nst3r/Burpy#23]
当POST表单中，字段值中包含<>时，经过burpy处理后，这段内容会被替换为空，导致异常。
比如Body中内容是这样的
`UserId=4577866&nickName=<aaabbb>&countryId=59&birthday=2000%2F03%2F03&userSign=`
当我Print到Burpy中时就成了：
`UserId=4577866&nickName= &countryId=59&birthday=2000%2F03%2F03&userSign=`

<>及其中间的部分去哪里了？

**Comment by mr-m0nst3r** [comment]
![image](https://user-images.githubusercontent.com/38524240/132969775-857fb690-c8b9-4707-9f4a-a6914baa4a56.png)

这个提示部分，是用HTML写的，所以只是没有显示出来，从数据上来看（见上图），这些数据是提交上去了。可以自己开个collaborator试试看

**Comment by hack2012** [comment]
我用1.7.37版本测试的，确实收不到，签名验证不通过。

**Comment by hack2012** [comment]
1.7.37中，使用img标签，在控制台打印时会解析这个标签。
