### ISSUE TITLE
When the Burppy start ， burpsuite is kill

### ISSUE THREAD

**Issue by Avenue-le** [mr-m0nst3r/Burpy#25]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Python: [e.g. python3.9]
 - Burpy: [e.g. v2.4.3]

**Burpy Scripts**
Add your script here for others to help with. DONT FORGET TO DELETE SENSITIVE INFO. 
（脚本请脱敏后提供）

**Additional context**

**Comment by Avenue-le** [comment]
插件已使用， bp 直接卡死

**Comment by mr-m0nst3r** [comment]
先在命令行直接运行一下脚本。

请按issue模板提供一些必要的信息，有助于帮你分析。

**Comment by mr-m0nst3r** [comment]
有问题再打开吧
