### ISSUE TITLE
autoenc和autodec功能没有奏效啊

### ISSUE THREAD

**Issue by gie-gie-gayhub** [mr-m0nst3r/Burpy#26]
大大大大大佬你好！勾上了autoenc和autodec功能，可是还是得我手动去点那个tab才会进行编码和解码。这个功能不是自动编码后发包并自动解码响应的么？

**Comment by mr-m0nst3r** [comment]
你好。

首先你需要把脚本先调试通。它会调用`encrypt`和`decrypt`两个函数，在`repeater`里面手动调一下看看是否正常加解密。

如果正常加解密，可以点开这个形状，在request中解密成原谅，直接点go发送，response会自动解密。

在Proxy->History或者你的记录里面不会自动加解密的，（好像是）

如果还不行，删除敏感的内容，可以把脚本弄上来看一下。

**Comment by mr-m0nst3r** [comment]
长时间没有回复，我先关闭了。如果还有问题再打开。
