### ISSUE TITLE
Auto ENC/DEC Display encoding is GBK by Default

### ISSUE THREAD

**Issue by breaking153** [mr-m0nst3r/Burpy#27]
but burpsuite maybe UTF-8 encoding which will cause ERROR on repeater on response text.
use Extension to decrypt:
![图片](https://user-images.githubusercontent.com/49428332/172102351-8e65da99-2a88-462f-b2d8-5df0ef2211df.png)
use Auto ENC/DEC to decrypt,it's GBK encoding so it has display error:
![图片](https://user-images.githubusercontent.com/49428332/172102461-4db6c9e4-7f6c-48b1-8a22-91166414c863.png)
change encoding to GBK and use Auto ENC/DEC to decrypt:
![图片](https://user-images.githubusercontent.com/49428332/172102695-8a070541-9aca-4931-81d7-035ad458da68.png)

maybe we can consider read burp's configuration to fix this?

**Comment by mr-m0nst3r** [comment]
I'm not sure whether we can read burps config, because the result is read from python, based64 encoded, so this leaves to our python script to deal with encoding.

If you got any good way to implement this, PRs are welcome.

BTW, you can speak Chinese, I'm Chinese. :D

**Comment by mr-m0nst3r** [comment]
Closing it. Reopen it if needed,
