### ISSUE TITLE
intruder module is with auto ENC/DEC is not reliable

### ISSUE THREAD

**Issue by breaking153** [mr-m0nst3r/Burpy#28]
while opening auto ENC/DEC option ,the result of the intruder is not reliable,i think its display error because flows still ENC and print in console successfully.
![图片](https://user-images.githubusercontent.com/49428332/172134735-d5ed5542-5317-4284-848b-2d4d5cf16da2.png)
![图片](https://user-images.githubusercontent.com/49428332/172134696-00805786-0d5c-41bb-a924-4ef2271f598e.png)

**Comment by mr-m0nst3r** [comment]
Hmm, interesting.

Maybe use python script as a intruder?

**Comment by mr-m0nst3r** [comment]
closing it. Reopen it if needed.
