### ISSUE TITLE
"start server"&"kill server"运行异常

### ISSUE THREAD

**Issue by Explorer1092** [mr-m0nst3r/Burpy#6]
Burpy版本:master 分支上的最新版
burp版本:2020.07
python环境：python3
操作系统：10.15.5 (19F101)

1、点击 "start server" 按钮时 "Server status" 显示 starting up ... starting up ... starting up ... starting up ... NOT running（同时内容显示不全）， "start server" 上的状态显示 Server stopped 
2、点击 "kill server" 按钮时 "Server status" 依然显示 starting up  "start server" 上的状态显示 Server stopped

**Comment by mr-m0nst3r** [comment]
建议排查一下是否python依赖库是否齐全，包括burpy的python依赖和自己python脚本中的依赖，如果方便把错误信息贴出来。

**Comment by Explorer1092** [comment]
> 建议排查一下是否python依赖库是否齐全，包括burpy的python依赖和自己python脚本中的依赖，如果方便把错误信息贴出来。

我发现了几个问题：
问题一：如果脚本的文件名里有特殊符号（比如 [ ]），有可能导致执行过程中出现问题
问题二：脚本如果执行报错，插件的console里没有错误提示。

**Comment by mr-m0nst3r** [comment]
@Explorer1092 
问题一：这个最好把文件名改一下。对这个bug我现在没有好的想法，欢迎提PR.

问题二：是的。因为这里面有从python到pyro，从pyro到Java的传递的过程，有时候错误提示会打不出来。这个是一个bug，但目前还没有比较好的方式修复。也欢迎担PR.

**Comment by wangqiang0092000** [comment]
> Burpy版本:master 分支上的最新版
> burp版本:2020.07
> python环境：python3
> 操作系统：10.15.5 (19F101)
> 
> 1、点击 "start server" 按钮时 "Server status" 显示 starting up ... starting up ... starting up ... starting up ... NOT running（同时内容显示不全）， "start server" 上的状态显示 Server stopped
> 2、点击 "kill server" 按钮时 "Server status" 依然显示 starting up "start server" 上的状态显示 Server stopped

我遇到了和你一样的问题，您是解决了吗？怎么解决的？

**Comment by rootphantomer** [comment]
> Burpy版本:master 分支上的最新版
> burp版本:2020.07
> python环境：python3
> 操作系统：10.15.5 (19F101)
> 
> 1、点击 "start server" 按钮时 "Server status" 显示 starting up ... starting up ... starting up ... starting up ... NOT running（同时内容显示不全）， "start server" 上的状态显示 Server stopped
> 2、点击 "kill server" 按钮时 "Server status" 依然显示 starting up "start server" 上的状态显示 Server stopped

目前也遇到这个问题，在macOS下。

**Comment by rootphantomer** [comment]
> > Burpy版本:master 分支上的最新版
> > burp版本:2020.07
> > python环境：python3
> > 操作系统：10.15.5 (19F101)
> > 1、点击 "start server" 按钮时 "Server status" 显示 starting up ... starting up ... starting up ... starting up ... NOT running（同时内容显示不全）， "start server" 上的状态显示 Server stopped
> > 2、点击 "kill server" 按钮时 "Server status" 依然显示 starting up "start server" 上的状态显示 Server stopped
> 
> 目前也遇到这个问题，在macOS下。

换了个python路径就好了

**Comment by mr-m0nst3r** [comment]
README 可能需要再完善一下。
这个工具依赖pyro4和我们python脚本中用的到库。

如果运行不了，可先检查该版本的python中有没有安装pyro4或者脚本中用到的库。
```
# for python3
python3 -m pip install pyro4
python3 -m pip install xxxx
```

如果仍然有问题再开，先关闭了各位。
